[[DATAIO]]
[appendix]
== Loading and Saving Data in R

This appendix will show you how to load and save data into R from plain-text files, R files, and Excel spreadsheets. It will also show you the R packages that you can use to load data from databases and other common programs, like SAS and MATLAB.

=== Data Sets in Base R

R comes with many data sets preloaded in the ++datasets++ package, which comes with base R. These data sets are not very interesting, but they give you a chance to test code or make a point without having to load a data set from outside R.(((data, loading/saving, data sets in base R)))(((base R)))(((data sets, in base R))) You can see a list of R's data sets as well as a short description of each by running:
[source,r]
----
help(package = "datasets")
----
To use a data set, just type its name.(((data sets, using))) Each data set is already presaved as an R object. For example: 
[source,r]
----
iris
##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa
----

However, R's data sets are no substitute for your own data, which you can load into R from a wide variety of file formats. But before you load any data files into R, you'll need to determine where your _working directory_ is.

=== Working Directory

Each time you open R, it links itself to a directory on your computer, which R calls the working directory. This is where R will look for files when you attempt to load them, and it is where R will save files when you save them. The location of your working directory will vary on different computers.(((data, loading/saving, working directory)))(((working directory, locating/changing)))((("getwd()"))) To determine which directory R is using as your working directory, run:
[source,r]
----
getwd()
## "/Users/garrettgrolemund"
----
You can place data files straight into the folder that is your working directory, or you can move your working directory to where your data files are. You can move your working directory to any folder on your computer with the function ++setwd++. Just give ++setwd++ the file path to your new working directory. I prefer to set my working directory to a folder dedicated to whichever project I am currently working on.(((working directory, moving)))((("setwd()"))) That way I can keep all of my data, scripts, graphs, and reports in the same place. For example: 
[source,r]
----
setwd("~/Users/garrettgrolemund/Documents/Book_Project")
----
If the file path does not begin with your root directory, R will assume that it begins at your current working directory. 

You can also change your working directory by clicking on Session > Set Working Directory > Choose Directory in the RStudio menu bar. The Windows and Mac GUIs have similar options. If you start R from a UNIX command line (as on Linux machines), the working directory will be whichever directory you were in when you called R.(((RStudio, changing working directory in)))(((Unix, working directory)))

You can see what files are in your working directory with ++list.files()++.  If you see the file that you would like to open in your working directory, then you are ready to proceed. How you open files in your working directory will depend on which type of file you would like to open.(((working directory, listing files in)))(((files, listing in working directory)))((("list.files()")))

=== Plain-text Files

Plain-text files are one of the most common ways to save data. They are very simple and can be read by many different computer programs—even the most basic text editors. For this reason, public data often comes as plain-text files. For example, the Census Bureau, the Social Security Administration, and the Bureau of Labor Statistics all make their data available as plain-text files.((("data", "loading/saving", "plain text files", id="ix_DLSplain", range="startofrange")))(((plain text files, benefits of)))((("files", "plain text files", seealso="plain text files")))

Here's how the royal flush data set from <<OBJECTS>> would appear as a plain-text file (I've added a value column):
----
"card", "suit", "value"
"ace", "spades", 14
"king", "spades", 13
"queen", "spades", 12
"jack", "spades", 11
"ten", "spades", 10
----

A plain-text file stores a table of data in a text document. Each row of the table is saved on its own line, and a simple convention is used to separate the cells within a row. Often cells are separated by a comma, but they can also be separated by a tab, a pipe delimiter (i.e., ++|++ ), or any other character. Each file only uses one method of separating cells, which minimizes confusion. Within each cell, data appears as you'd expect to see it, as words and numbers.(((plain text files, table structure in))) 

All plain-text files can be saved with the extension _.txt_ (for text), but sometimes a file will receive a special extension that advertises how it separates data-cell entries. Since entries in the data set mentioned earlier are separated with a comma, this file would be a _comma-separated-values_ file and would usually be saved with the extension _.csv_. ((("comma-separated-values file (.csv)")))

==== read.table

To load a plain-text file, use ++read.table++.(((plain text files, loading)))((("read.table"))) The first argument of ++read.table++ should be the name of your file (if it is in your working directory), or the file path to your file (if it is not in your working directory). If the file path does not begin with your root pass:[<phrase role="keep-together">directory,</phrase>] R will append it to the end of the file path that leads to your working directory.You can give ++read.table++ other arguments as well. The two most important are ++sep++ and ++header++. 

If the royal flush data set was saved as a file named _poker.csv_ in your working directory, you could load it with:
[source,r]
----
poker <- read.table("poker.csv", sep = ",", header = TRUE)
----

===== sep

Use ++sep++ to tell ++read.table++ what character your file uses to separate data entries. To find this out, you might have to open your file in a text editor and look at it. If you don't specify a ++sep++ argument, ++read.table++ will try to separate cells whenever it comes to white space, such as a tab or space. R won't be able to tell you if ++read.table++ does this correctly or not, so rely on it at your own risk.(((plain text files, sep argument)))(((sep argument))) 

===== header

Use ++header++ to tell ++read.table++ whether the first line of the file contains variable names instead of values. If the first line of the file is a set of variable names, you should set ++header = TRUE++.(((plain text files, header argument)))(((header argument)))

===== na.strings

Oftentimes data sets will use special symbols to represent missing information.(((plain text files, na.strings argument)))(((na.strings argument)))(((missing information, in plain text files)))(((files, missing information in))) If you know that your data uses a certain symbol to represent missing entries, you can tell ++read.table++ (and the preceding functions) what the symbol is with the ++na.strings++ argument. ++read.table++ will convert all instances of the missing information symbol to ++NA++, which is R's missing information symbol (see <<MISSING>>).

For example, your poker data set contained missing values stored as a ++.++, like this:
[source,r]
----
## "card","suit","value"
## "ace"," spades"," 14"
## "king"," spades"," 13"
## "queen",".","."
## "jack",".","."
## "ten",".","."
----
You could read the data set into R and convert the missing values into NAs as you go with the command:
[source,r]
----
poker <- read.table("poker.csv", sep = ",", header = TRUE, na.string = ".")
----
R would save a version of ++poker++ that looks like this:
[source,r]
----
##  card    suit value
##   ace  spades    14
##  king  spades    13
## queen    <NA>    NA
##  jack    <NA>    NA
##   ten    <NA>    NA
----

===== skip and nrow

Sometimes a plain-text file will come with introductory text that is not part of the data set. Or, you may decide that you only wish to read in part of a data set. You can do these things with the ++skip++ and ++nrow++ arguments. Use ++skip++ to tell R to skip a specific number of lines before it starts reading in values from the file. Use ++nrow++ to tell R to stop reading in values after it has read in a certain number of lines.(((plain text files, skip argument)))(((skip argument)))(((plain text files, nrow argument)))(((nrow argument))) 

For example, imagine that the complete royal flush file looks like this:
[source,r]
----
This data was collected by the National Poker Institute. 
We accidentally repeated the last row of data.

"card", "suit", "value"
"ace", "spades", 14
"king", "spades", 13
"queen", "spades", 12
"jack", "spades", 11
"ten", "spades", 10
"ten", "spades", 10
----
You can read just the six lines (five rows plus a header) that you want with:
[source,r]
----
read.table("poker.csv", sep = ",", header = TRUE, skip = 3, nrow = 5)
##    card    suit value
## 1   ace  spades    14
## 2  king  spades    13
## 3 queen  spades    12
## 4  jack  spades    11
## 5   ten  spades    10
----
Notice that the header row doesn't count towards the total rows allowed by ++nrow++.

===== stringsAsFactors

R reads in numbers just as you'd expect, but when R comes across character strings (e.g., letters and words) it begins to act strangely.(((plain text files, stringAsFactors argument)))(((stringAsFactors argument)))(((character strings, preventing factoring of)))((("factoring, preventing"))) R wants to convert every character string into a factor. This is R's default behavior, but I think it is a mistake. Sometimes factors are useful. At other times, they're clearly the wrong data type for the job. Also factors cause weird behavior, especially when you want to display data. This behavior can be surprising if you didn't realize that R converted your data to factors. In general, you'll have a smoother R experience if you don't let R make factors until you ask for them. Thankfully, it is easy to do this.

Setting the argument ++stringsAsFactors++ to ++FALSE++ will ensure that R saves any character strings in your data set as character strings, not factors. To use ++stringsAsFactors++, you'd write:
[source,r]
----
read.table("poker.csv", sep = ",", header = TRUE, stringsAsFactors = FALSE)
----
If you will be loading more than one data file, you can change the default factoring behavior at the global level with:
[source,r]
----
options(stringsAsFactors = FALSE)
----
This will ensure that all strings will be read as strings, not as factors, until you end your R session, or rechange the global default by running:
[source,r]
----
options(stringsAsFactors = TRUE)
----

==== The read Family

R also comes with some prepackaged short cuts for ++read.table++, shown in <<TABLE-READ-SHORTCUTS>>.((("read.table")))(((plain text files, loading)))(((read.csv)))(((read.delim)))(((read.csv2)))(((read.delim2))) 

[[TABLE-READ-SHORTCUTS]]
.R's read functions. You can overwrite any of the default arguments as pass:[<phrase role="keep-together">necessary.</phrase>]
[width="90%",options="header"]
|=======
|Function|Defaults|Use
|++read.table++|sep = " ", header = FALSE| General-purpose read function
|++read.csv++|sep = ",", header = TRUE|Comma-separated-variable (CSV) files
|++read.delim++|sep = "\t", header = TRUE|Tab-delimited files
|++read.csv2++|sep = ";", header = TRUE, dec = ","| CSV files with European decimal format
|++read.delim2++|sep = "\t", header = TRUE, dec = ","| Tab-delimited files with European decimal format
|=======

The first shortcut, ++read.csv++, behaves just like ++read.table++ but automatically sets ++sep = ","++ and ++header = TRUE++, which can save you some typing:
[source,r]
----
poker <- read.csv("poker.csv")
----
++read.delim++ automatically sets ++sep++ to the tab character, which is very handy for reading tab delimited files. These are files where each cell is separated by a tab. ++read.delim++ also sets ++header = TRUE++ by default. 

++read.delim2++ and ++read.csv2++ exist for European R users. These functions tell R that the data uses a comma instead of a period to denote decimal places. (If you're wondering how this works with CSV files, CSV2 files usually separate cells with a semicolon, not a comma.)

.Import Dataset
[TIP]
===============================
You can also load plain text files with RStudio's Import Dataset pass:[<phrase role="keep-together">button,</phrase>] as described in <<LOADING>>. Import Dataset provides a GUI version of ++read.table++.
===============================


==== read.fwf

One type of plain-text file defies the pattern by using its layout to separate data cells. Each row is placed in its own line (as with other plain-text files), and then each column begins at a specific number of characters from the lefthand side of the document. To achieve this, an arbitrary number of character spaces is added to the end of each entry to correctly position the next entry. These documents are known as _fixed-width files_ and usually end with the extension _.fwf_.(((plain text files, read.fwf)))(((read.fwf)))((("fixed-width files (.fwf)")))((("files", "fixed-width files (.fwf)"))) 

Here's one way the royal flush data set could look as a fixed-width file. In each row, the suit entry begins exactly 10 characters from the start of the line. It doesn't matter how many characters appeared in the first cell of each row:
----
card      suit       value
ace       spades     14
king      spades     13  
queen     spades     12  
jack      spades     11  
10        spades     10
----

Fixed-width files look nice to human eyes (but no better than a tab-delimited file); however, they can be difficult to work with. Perhaps because of this, R comes with a function for reading fixed-width files, but no function for saving them. Unfortunately, US government agencies seem to like fixed-width files, and you'll likely encounter one or more during your career.

You can read fixed-width files into R with the function ++read.fwf++. The function takes the same arguments as ++read.table++ but requires an additional argument, ++widths++, which should be a vector of numbers. Each __i__th entry of the ++widths++ vector should state the width (in characters) of the __i__th column of the data set.

If the aforementioned fixed-width royal flush data was saved as _poker.fwf_ in your working directory, you could read it with:
[source,r]
----
poker <- read.fwf("poker.fwf", widths = c(10, 7, 6), header = TRUE)
----

==== HTML Links

Many data files are made available on the Internet at their own web address.(((plain text files, HTML links in)))((("HTML links, in plain text files")))((("files", "HTML links in"))) If you are connected to the Internet, you can open these files straight into R with ++read.table++, ++read.csv++, etc. You can pass a web address into the file name argument for any of R's data-reading functions. As a result, you could read in the poker data set from a web address like _http://.../poker.csv_ with:
[source,r]
----
poker <- read.csv("http://.../poker.csv")
----
Just make sure that the web address links directly to the file and not to a web page that links to the file. Usually, when you visit a data file's web address, the file will begin to download or the raw data will appear in your browser window.

Note that websites that begin with _https://_ are secure websites, which means R may not be able to access the data provided at these links.

==== Saving Plain-Text Files

Once your data is in R, you can save it to any file format that R supports. If you'd like to save it as a plain-text file, you can use the +write+ family of functions. The three basic write functions appear in <<WRITE_TABLE>>. Use ++write.csv++ to save your data as a __.csv__ file and ++write.table++ to save your data as a tab delimited document or a document with more exotic separators.(((plain text files, saving)))(((write.csv)))(((write.csv2)))(((write.table)))

[[WRITE_TABLE]]
.R saves data sets to plain-text files with the write family of functions
[width="100%",options="header"]
|=======
|File format|Function and syntax
|__.csv__|++write.csv(r_object, file = filepath, row.names = FALSE)++
|__.csv__ (with European decimal notation)|++write.csv2(r_object, file = filepath, row.names = FALSE)++
|tab delimited|++write.table(r_object, file = filepath, sep = "\t", row.names=FALSE)++
|=======

The first argument of each function is the R object that contains your data set. The ++file++ argument is the file name (including extension) that you wish to give the saved data. By default, each function will save your data into your working directory. However, you can supply a file path to the file argument. R will oblige by saving the file at the end of the file path. If the file path does not begin with your root directory, R will append it to the end of the file path that leads to your working directory.

For example, you can save the (hypothetical) poker data frame to a subdirectory named _data_ within your working directory with the command:
[source,r]
----
write.csv(poker, "data/poker.csv", row.names = FALSE)
----

Keep in mind that ++write.csv++ and ++write.table++ cannot create new directories on your computer. Each folder in the file path must exist before you try to save a file with it. 

The ++row.names++ argument prevents R from saving the data frame's row names as a column in the plain-text file. You might have noticed that R automatically names each row in a data frame with a number. For example, each row in our poker data frame appears with a number next to it: 
[source,r]
----
poker
##    card   suit value
## 1   ace spades    14
## 2  king spades    13
## 3 queen spades    12
## 4  jack spades    11
## 5    10 spades    10
----
These row numbers are helpful, but can quickly accumulate if you start saving them. R will add a new set of numbers by default each time you read the file back in. Avoid this by always setting ++row.names = FALSE++ when you use a function in the ++write++ family.


==== Compressing Files

To compress a plain-text file, surround the file name or file path with the function ++bzfile++, ++gzfile++, or ++xzfile++.(((plain text files, compressing)))(((bzfile function)))(((gzfile function)))(((xzfile function))) For example:
[source,r]
----
write.csv(poker, file = bzfile("data/poker.csv.bz2"), row.names = FALSE)
----
Each of these functions will compress the output with a different type of compression format, shown in <<COMPRESSION_TABLE>>.(((bzip2 compression)))(((gnu zip (gzip) compression)))(((xz compression))) 

[[COMPRESSION_TABLE]]
.R comes with three helper functions for compressing files
[width="90%",options="header"]
|=======
|Function|Compression type
|++bzfile++|bzip2
|++gzfile++|gnu zip (gzip)
|++xzfile++|xz compression
|=======

It is a good idea to adjust your file's extension to reflect the compression. R's ++read++ functions will open plain-text files compressed in any of these formats. For example, you could read a compressed file named _poker.csv.bz2_ with:
[source,r]
----
read.csv("poker.csv.bz2")
----
or: 
[source,r]
----
read.csv("data/poker.csv.bz2")
----
depending on where the file is saved.(((range="endofrange", startref="ix_DLSplain")))

=== R Files

R provides two file formats of its own for storing data, _.RDS_ and _.RData_. RDS files can store a single R object, and RData files can store multiple R objects.(((data, loading/saving, R files)))((("RDS files", "opening")))(((RData files, opening)))(((R files, opening/saving)))(((files, R files, opening/saving)))(((files, RData files, opening)))((("files", "RDS files", "opening")))

You can open a RDS file with ++readRDS++. For example, if the royal flush data was saved as _poker.RDS_, you could open it with:
[source,r]
----
poker <- readRDS("poker.RDS")
----

Opening RData files is even easier. Simply run the function ++load++ with the file:
[source,r]
----
load("file.RData")
----

There's no need to assign the output to an object. The R objects in your RData file will be loaded into your R session with their original names. RData files can contain multiple R objects, so loading one may read in multiple objects. ++load++ doesn't tell you how many objects it is reading in, nor what their names are, so it pays to know a little about the RData file before you load it.

If worse comes to worst, you can keep an eye on the environment pane in RStudio as you load an RData file. It displays all of the objects that you have created or loaded during your R session. Another useful trick is to put parentheses around your load command like so, ++(load("poker.RData"))++. This will cause R to print out the names of each object it loads from the file.

Both ++readRDS++ and ++load++ take a file path as their first argument, just like R's other read and write functions. If your file is in your working directory, the file path will be the pass:[<phrase role="keep-together">file name.</phrase>](((readRDS function)))(((load function)))

==== Saving R Files

You can save an R object like a data frame as either an RData file or an RDS file. RData files can store multiple R objects at once, but RDS files are the better choice because they foster reproducible code.(((RData files, saving)))((("RDS files", "saving")))(((RData files, vs. RDS files)))(((RDS files, vs. RData files)))(((files, RData files, saving)))(((files, RData files, vs. RDS files)))((("files", "RDS files", "saving")))(((files, RDS files, vs. RData files)))

To save data as an RData object, use the ++save++ function. To save data as a RDS object, use the ++saveRDS++ function. In each case, the first argument should be the name of the R object you wish to save. You should then include a file argument that has the file name or file path you want to save the data set to.(((save function)))(((saveRDS function)))

For example, if you have three R objects, ++a++, ++b++, and ++c++, you could save them all in the same RData file and then reload them in another R session:

[source,r]
----
a <- 1
b <- 2
c <- 3
save(a, b, c, file = "stuff.RData")
load("stuff.RData")
----
However, if you forget the names of your objects or give your file to someone else to use, it will be difficult to determine what was in the file—even after you (or they) load it. The user interface for RDS files is much more clear. You can save only one object per file, and whoever loads it can decide what they want to call their new data. As a bonus, you don't have to worry about ++load++ overwriting any R objects that happened to have the same name as the objects you are loading:
[source,r]
----
saveRDS(a, file = "stuff.RDS") 
a <- readRDS("stuff.RDS")
----
Saving your data as an R file offers some advantages over saving your data as a plain-text file. R automatically compresses the file and will also save any R-related metadata associated with your object. This can be handy if your data contains factors, dates and times, or class attributes. You won't have to reparse this information into R the way you would if you converted everything to a text file.(((plain text files, vs. R files)))(((R files, vs. plain text files)))(((files, R files, vs. plain text files))) 

On the other hand, R files cannot be read by many other programs, which makes them inefficient for sharing. They may also create a problem for long-term storage if you don't think you'll have a copy of R when you reopen the files.

=== Excel Spreadsheets

Microsoft Excel is a popular spreadsheet program that has become almost industry standard in the business world. There is a good chance that you will need to work with an Excel spreadsheet in R at least once in your career. You can read spreadsheets into R and also save R data as a spreadsheet in a variety of ways.((("data", "loading/saving", "Excel spreadsheets", id="ix_DLSspread", range="startofrange")))((("spreadsheets", see="Excel spreadsheets"))) 

==== Export from Excel

The best method for moving data from Excel to R is to export the spreadsheet from Excel as a __.csv__ or __.txt__ file. Not only will R be able to read the text file, so will any other data analysis software. Text files are the lingua franca of data storage.(((plain text files, benefits of)))(((Excel spreadsheets, exporting data)))

Exporting the data solves another difficulty as well. Excel uses proprietary formats and metadata that will not easily transfer into R. For example, a single Excel file can include multiple spreadsheets, each with their own columns and macros. When Excel exports the file as a __.csv__ or __.txt__, it makes sure this format is transferred into a plain-text file in the most appropriate way. R may not be able to manage the conversion as efficiently.

To export data from Excel, open the Excel spreadsheet and then go to Save As in the Microsoft Office Button menu. Then choose CSV in the Save as type box that appears and save the files. You can then read the file into R with the ++read.csv++ function.((("comma-separated-values file (.csv)")))

==== Copy and Paste

You can also copy portions of an Excel spreadsheet and paste them into R. To do this, open the spreadsheet and select the cells you wish to read into R. Then select Edit > Copy in the menu bar—or use a keyboard shortcut—to copy the cells to your clipboard.(((Excel spreadsheets, copying/pasting data from)))((("copy/paste, from Excel spreadsheets")))(((read.table)))

On most operating systems, you can read the data stored in your clipboard into R with: 
[source,r]
----
read.table("clipboard")
----
On Macs you will need to use:
[source,r]
----
read.table(pipe("pbpaste"))
----
If the cells contain values with spaces in them, this will disrupt ++read.table++. You can try another ++read++ function (or just formally export the data from Excel) before reading it into R.

==== XLConnect

Many packages have been written to help you read Excel files directly into R. Unfortunately, many of these packages do not work on all operating systems. Others have been made out of date by the _.xlsx_ file format. One package that does work on all file systems (and gets good reviews) is the XLConnect package.(((Excel spreadsheets, XLConnect package)))(((XLConnect package)))(((packages, XLConnect))) To use it, you'll need to install and load the package:
[source,r]
----
install.packages("XLConnect")
library(XLConnect)
----
XLConnect relies on Java to be platform independent. So when you first open XLConnect, RStudio may ask to download a Java Runtime Environment if you do not already have one.

==== Reading Spreadsheets

You can use XLConnect to read in an Excel spreadsheet with either a one- or a two-step process.(((Excel spreadsheets, reading)))(((loadWorkbook))) I'll start with the two-step process. First, load an Excel workbook with ++loadWorkbook++. ++loadWorkbook++ can load both _.xls_ and _.xlsx_ files. It takes one argument: the file path to your Excel workbook (this will be the name of the workbook if it is saved in your working directory):
[source,r]
----
wb <- loadWorkbook("file.xlsx")
----
Next, read a spreadsheet from the workbook with ++readWorksheet++, which takes several arguments.(((readWorksheet)))(((sheet argument))) The first argument should be a workbook object created with ++loadWorkbook++. The next argument, ++sheet++, should be the name of the spreadsheet in the workbook that you would like to read into R. This will be the name that appears on the bottom tab of the spreadsheet. You can also give ++sheet++ a number, which specifies the sheet that you want to read in (one for the first sheet, two for the second, and so on). 

++readWorksheet++ then takes four arguments that specify a bounding box of cells to read in: ++startRow++, ++startCol++, ++endRow++, and ++endCol++. Use ++startRow++ and ++startCol++ to describe the cell in the top-left corner of the bounding box of cells that you wish to read in. Use ++endRow++ and ++endCol++ to specify the cell in the bottom-right corner of the bounding box. Each of these arguments takes a number. If you do not supply bounding arguments, ++readWorksheet++ will read in the rectangular region of cells in the spreadsheet that appears to contain data. ++readWorksheet++ will assume that this region contains a header row, but you can tell it otherwise with ++header = FALSE++.(((bounding arguments)))(((startRow argument)))(((startCol argument)))(((endRow argument)))(((endCol argument)))

So to read in the first worksheet from ++wb++, you could use:
[source,r]
----
sheet1 <- readWorksheet(wb, sheet = 1, startRow = 0, startCol = 0, 
  endRow = 100, endCol = 3)
----
R will save the output as a data frame. All of the arguments in ++readWorkbook++ except the first are vectorized, so you can use it to read in multiple sheets from the same workbook at once (or multiple cell regions from a single worksheet). In this case, ++readWorksheet++ will return a list of data frames.

You can combine these two steps with ++readWorksheetFromFile++. It takes the file argument from ++loadWorkbook++ and combines it with the arguments from ++readWorksheet++. You can use it to read one or more sheets straight from an Excel file:
[source,r]
----
sheet1 <- readWorksheetFromFile("file.xlsx", sheet = 1, startRow = 0, 
  startCol = 0, endRow = 100, endCol = 3)
----

==== Writing Spreadsheets

Writing to an Excel spreadsheet is a four-step process.(((Excel spreadsheets, writing to)))(((createSheet))) First, you need to set up a workbook object with ++loadWorkbook++. This works just as before, except if you are not using an existing Excel file, you should add the argument ++create = TRUE++. XLConnect will create a blank workbook. When you save it, XLConnect will write it to the file location that you specified here with ++loadWorkbook++:
[source,r]
----
wb <- loadWorkbook("file.xlsx", create = TRUE)
----
Next, you need to create a worksheet inside your workbook object with ++createSheet++. Tell ++createSheet++ which workbook to place the sheet in and which to use for the sheet.
[source,r]
----
createSheet(wb, "Sheet 1")
----
Then you can save your data frame or matrix to the sheet with ++writeWorksheet++.(((writeWorksheet))) The first argument of ++writeWorksheet++, ++object++, is the workbook to write the data to. The second argument, ++data++, is the data to write. The third argument, ++sheet++, is the name of the sheet to write it to. The next two arguments, ++startRow++ and ++startCol++, tell R where in the spreadsheet to place the upper-left cell of the new data. These arguments each default to 1. Finally, you can use ++header++ to tell R whether your column names should be written with the data:
[source,r]
----
writeWorksheet(wb, data = poker, sheet = "Sheet 1")
----
Once you have finished adding sheets and data to your workbook, you can save it by running ++saveWorkbook++ on the workbook object. R will save the workbook to the file name or path you provided in ++loadWorkbook++. If this leads to an existing Excel file, R will overwrite it. If it leads to a new file, R will create it.(((saveWorkbook)))(((writeWorksheetToFile)))(((XLConnect package)))(((packages, XLConnect)))(((Excel spreadsheets, XLConnect package)))

You can also collapse these steps into a single call with ++writeWorksheetToFile++, like this:
[source,r]
----
writeWorksheetToFile("file.xlsx", data = poker, sheet = "Sheet 1", 
  startRow = 1, startCol = 1)
----
The XLConnect package also lets you do more advanced things with Excel spreadsheets, such as writing to a named region in a spreadsheet, working with formulas, and assigning styles to cells.(((range="endofrange", startref="ix_DLSspread"))) You can read about these features in XLConnect's vignette, which is accessible by loading XLConnect and then running:
[source,r]
----
vignette("XLConnect")
----

=== Loading Files from Other Programs

You should follow the same advice I gave you for Excel files whenever you wish to work with file formats native to other programs: open the file in the original program and export the data as a plain-text file, usually a CSV. This will ensure the most faithful transcription of the data in the file, and it will usually give you the most options for customizing how the data is transcribed.(((data, loading/saving, loading files from other programs)))(((files, loading/saving from other programs)))

Sometimes, however, you may acquire a file but not the program it came from. As a result, you won't be able to open the file in its native program and export it as a text file. In this case, you can use one of the functions in <<OTHER_FORMATS>> to open the file. These functions mostly come in R's ++foreign++ package. Each attempts to read in a different file format with as few hiccups as possible.(((foreign package)))(((packages, foreign)))((("ERSI ArcGIS format")))((("Matlab format")))((("read.shapefile function")))((("readMat function")))((("shapefiles library")))((("R.matlab library")))

[[OTHER_FORMATS]]
.A number of functions will attempt to read the file types of other data-analysis programs
[width="90%",options="header"]
|=======
|File format|Function|Library
|ERSI ArcGIS|++read.shapefile++|shapefiles
|Matlab|++readMat++|R.matlab
|minitab|++read.mtp++|foreign
|SAS (permanent data set)|++read.ssd++|foreign
|SAS (XPORT format)|++read.xport++|foreign
|SPSS|++read.spss++|foreign
|Stata|++read.dta++|foreign
|Systat|++read.systat++|foreign
|=======

==== Connecting to Databases

You can also use R to connect to a database and read in data.(((data, loading/saving, in databases)))((("databases, connecting to")))(((RODBC package)))(((packages, RODBC)))(((DBI package)))(((packages, DBI))) How you do this will depend on the database management system that you use. Working with a database will require experience that goes beyond the skill set of a typical R user. However, if you are interested in doing this, the best place to start is by downloading these R packages and reading their documentation.((("minitab format")))((("SAS (permanent data set) format")))((("SAS (XPORT format)")))((("SPSS format")))((("Stata format")))((("Systat format")))((("read.mtp function")))((("read.ssd function")))((("read.xport function")))((("read.spss function")))((("read.dta function")))((("read.systat function")))

Use the RODBC package to connect to databases through an ODBC connection. 

Use the DBI package to connect to databases through individual drivers. The DBI package provides a common syntax for working with different databases. You will have to download a database-specific package to use in conjunction with DBI. These packages provide the API for the native drivers of different database programs. For MySQL use RMySQL, for SQLite use RSQLite, for Oracle use ROracle, for PostgreSQL use RPostgreSQL, and for databases that use drivers based on the Java Database Connectivity (JDBC) API use RJDBC. Once you have loaded the appropriate driver package, you can use the commands provided by DBI to access your database.