# (PART) Part 2 {-}

# Project 2: Playing Cards

This project--which spans the next four chapters--will teach you how to store, retrieve, and change data values in your computer's memory. These skills will help you save and manage data without accumulating errors. In the project, you'll design a deck of playing cards that you can shuffle and deal from. Best of all, the deck will remember which cards have been dealt--just like a real deck. You can use the deck to play card games, tell fortunes, and test card-counting strategies.

Along the way, you will learn how to:

* Save new types of data, like character strings and logical values
* Save a data set as a vector, matrix, array, list, or data frame
* Load and save your own data sets with R
* Extract individual values from a data set
* Change individual values within a data set
* Write logical tests
* Use R's missing-value symbol, NA

To keep the project simple, I've divided it into four tasks. Each task will teach you a new skill for managing data with R:

**Task 1: build the deck**  
  In [R Objects], you will design and build a virtual deck of playing cards. This will be a complete data set, just like the ones you will use as a data scientist. You'll need to know how to use R's data types and data structures to make this work.
  
**Task 2: write functions that deal and shuffle**  
  Next, in [R Notation], you will write two functions to use with the deck. One function will deal cards from the deck, and the other will reshuffle the deck. To write these functions, you'll need to know how to extract values from a data set with R.
  
**Task 3: change the point system to suit your game**  
  In [Modifying Values], you will use R's notation system to change the point values of your cards to match the card games you may wish to play, like war, hearts, or blackjack. This will help you change values in place in existing data sets.

**Task 4: manage the state of the deck**  
  Finally, in [Environments], you will make sure that your deck remembers which cards it has dealt. This is an advanced task, and it will introduce R's environment system and scoping rules. To do it successfully, you will need to learn the minute details of how R looks up and uses the data that you have stored in your computer.
